Add proxy configuration for primary site templates
foxglove/helm-charts pull request #106
Opened 2024-12-05 12:24 UTC by fabriciolelis

### Changelog

### Docs

### Description

<table><tr><th>Before</th><th>After</th></tr><tr><td>

</td><td>

</td></tr></table>

2024-12-05 14:57 UTC, sofuture requested changes

2024-12-05 14:57 UTC, sofuture commented on charts/primary-site/values.yaml
> +proxy:
Can we move these under `globals`?

2024-12-05 15:10 UTC, fabriciolelis commented on charts/primary-site/values.yaml
> +proxy:
Yes, it was moved on the new commit

2024-12-05 15:20 UTC, sofuture approved these changes

2024-12-05 15:20 UTC, merged

2024-12-12 04:19 UTC, defunctzombie commented on charts/primary-site/values.yaml
> +    enabled: true
@jeff-foxglove it seems weird to me that we defaulted this to _true_ and tell people to set it to false. The comment and decision seems backwards. Proxy should be the exception not the default.